version: "3.9"
services:
  front:
    build: front/
    ports:
      - 80:80
    # environment:
    #   - REACT_APP_BACK_HOST=localhost
    #   - REACT_APP_BACK_PORT=8080
    depends_on:
      - back
  back:
    build: back/
    ports:
      - 8080:8080
    environment:
      - JDBC_URL=jdbc:mysql://db/expenses
      - JDBC_USER=root
      - JDBC_PASSWORD=pass
      - JDBC_DRIVER=com.mysql.cj.jdbc.Driver
    depends_on:
      - db
    restart: on-failure
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=expenses
    volumes:
      - ./mysql:/var/lib/mysql